# Generated by Django 4.2.7 on 2025-11-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('volume', models.BigIntegerField()),
                ('trade_date', models.DateTimeField()),
                ('option_type', models.CharField(max_length=10)),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField()),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MarketNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(blank=True, max_length=10)),
                ('headline', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
