services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      - DEBUG=1
      - DB_ENGINE=sqlite
      - SQLITE_NAME=/app/data/db.sqlite3
    volumes:
      - ./backend:/app
      - sqlite_data:/app/data
    # Uncomment for debugging:
    # command: python manage_debug.py runserver 0.0.0.0:8000

  angular-frontend:
    build: ./angular-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  sqlite_data:
