# Generated by Django 4.2.7 on 2025-11-06 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('exchange', models.CharField(blank=True, max_length=50)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('volume', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionsChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('CALL', 'Call'), ('PUT', 'Put')], max_length=10)),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField()),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('bid', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ask', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('implied_volatility', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('delta', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('gamma', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('theta', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('vega', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('rho', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('open_interest', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='options.stock')),
            ],
        ),
    ]
